export const UI_COPY = {
  common: {
    loading: "로딩 중...",
    droppedParamsPrefix: "파라미터가 자동으로 다운그레이드되었습니다:",
    copy: "복사",
    requestIdLabel: "요청 ID（request_id）",
  },
  brand: {
    appName: "ainovel Atelier",
  },
  nav: {
    home: "홈",
    groupWorkbench: "프로젝트 워크벤치",
    groupView: "보기",
    groupAiConfig: "프로젝트 구성",
    groupAdvancedDebug: "고급 디버그",
    groupAdmin: "관리",

    wizard: "시작 마법사",
    projectSettings: "프로젝트 설정",
    characters: "캐릭터 카드",
    outline: "개요",
    writing: "글쓰기",
    tasks: "작업 센터",
    structuredMemory: "그래프 기반 데이터",
    numericTables: "수치 테이블 (NumericTables)",
    chapterAnalysis: "스토리 기억",
    preview: "미리보기",
    reader: "읽기",
    export: "내보내기",

    worldBook: "월드북",
    rag: "지식 베이스 (RAG)",
    search: "검색 엔진",
    graph: "그래프/관계",
    fractal: "분형(Fractal)",
    styles: "스타일",
    prompts: "모델 설정",
    promptStudio: "프롬프트 스튜디오",
    promptTemplates: "프롬프트 템플릿",
    foreshadows: "복선",
    dataImport: "가져오기",
    adminUsers: "사용자 관리",
    help: "용어 / 도움말",

    navMenu: "탐색 메뉴",
    openNav: "내비게이션 열기",
    closeNav: "내비게이션 닫기",
    advancedDebugToggle: "고급 디버그 표시 (문제 해결 전용)",
    chooseProjectHint: "편집 페이지로 이동하려면 프로젝트를 선택해 주세요.",
    currentProject: "현재 프로젝트",
    backToHome: "홈으로 돌아가기",
  },
  notFound: {
    title: "페이지가 존재하지 않습니다",
    description: "요청하신 페이지를 찾을 수 없습니다. 아래 링크를 이용해 보세요.",
  },
  help: {
    title: "용어 / 도움말",
    subtitle: "자주 쓰는 용어 빠른 참조 + 페이지 설명 템플릿 (사용 시기 / 위험 / 예시).",
    termsTitle: "자주 쓰는 용어 (빠른 참조)",
    terms: [
      { label: "프롬프트 (prompt)", description: "모델에 제공되는 명령어 텍스트입니다. 일반적으로 “목표”로 시작합니다. + 제한. + 입력./출력 형식으로 구성됩니다.。" },
      { label: "벡터화（embedding）", description: "텍스트를 벡터로 변환하여 검색에 활용합니다. 모델/인터페이스 설정이 필요하며 비용과 시간이 소요될 수 있습니다." },
      { label: "재순위 정렬(rerank)", description: "후보 결과를 재정렬하여 검색 품질을 높여요. 일반적으로 추가 연산이 한 번 발생해요." },
      { label: "검색 증강 생성 (RAG)", description: "관련 단락을 먼저 검색한 후 생성 컨텍스트에 주입합니다. 일관성 및 인용 강화에 사용됩니다." },
      { label: "지식 베이스 (KB)", description: "RAG의 데이터 그룹 및 가중치 설정 단위입니다. 용도별로 분리하여 개별 활성화/정렬할 수 있습니다." },
      { label: "요청 ID（request_id）", description: "백엔드가 요청마다 생성하는 추적 식별자입니다. 오류/예외 발생 시 우선적으로 기록해 두세요." },
      { label: "JSON", description: "구조화된 데이터 형식으로, 고급 디버깅 및 가져오기/내보내기 시 자주 사용됩니다." },
    ],
    tipsTitle: "문제 해결 팁",
    tips: [
      "오류 발생 시: 요청 ID（request_id）와 재현 단계（무엇을 클릭/입력했는지）를 먼저 기록해 주세요.",
      "“로딩 속도가 느립니다”라는 메시지가 표시될 때./“불안정” 상태가 발생하면, 먼저 인덱스를 재구축할 필요가 있는지 확인해 보세요./데이터 저장 및 대량 데이터로 인해 페이지 분할이 필요한지 여부./압박감을 조성하다.。",
    ],
  },
  search: {
    title: "검색 엔진",
    subtitle: "VSCode 전체 프로젝트 용어 검색 (다양한 소스에서 수집, 필터링 및 연결 기능 제공; 기존 ‘용어집’ 대체)./“용어 매핑” 항목.",
    queryPlaceholder: "키워드 입력…",
    search: "검색",
    clear: "비우기",
    sourcesTitle: "출처",
    sourceLabels: {
      chapter: "챕터",
      outline: "개요",
      worldbookEntry: "월드북",
      character: "캐릭터",
      storyMemory: "스토리 기억",
      sourceDocument: "문서 가져오기",
      projectTableRow: "수치 테이블",
      memoryEntity: "그래프 엔티티",
      memoryRelation: "인물 관계",
      memoryEvidence: "관계 근거",
    },
    emptyHint: "결과가 없습니다",
    loadMore: "더 보기",
    jump: "이동",
    jumpDisabledHint: "이 출처는 현재 이동을 지원하지 않습니다（ID를 복사하여 수동으로 찾을 수 있습니다）.",
    copyId: "ID 복사",
    copyIdFailTitle: "복사 실패: 수동으로 복사해 주세요",
    copiedId: "ID가 복사되었습니다",
    copyLocator: "locator 복사",
    copyLocatorFailTitle: "복사 실패: locator를 수동으로 복사해 주세요",
    copiedLocator: "locator가 복사되었습니다",
    copyFailedToast: "자동 복사에 실패했습니다. 수동 복사 창을 열었습니다.",
    debugTitle: "Debug",
  },
  chapterAnalysis: {
    introTitle: "용도 설명",
    introLine1: "“스토리라인 메모 표시” 기능을 사용하여 텍스트 내에서 해당 부분을 강조 표시하여 원본 텍스트와 비교하고 특정 부분을 쉽게 찾을 수 있도록 합니다. 강조 표시된 부분을 클릭하거나 오른쪽 목록에서 해당 항목을 선택하면 해당 부분으로 바로 이동합니다.。",
    introLine2: "주의: 여기서는 스토리 기억 (Hook/복선/플롯/요약)을 관리하며, 세계관 설정 (인물/장소/아이템)과는 다릅니다.",
    entryLine: "입력: 글쓰기 페이지 (선택한 장)→ 오른쪽 상단의 “주석 추적” 기능 (필요). chapterId）。",
    storyMemoryTitle: "스토리 기억(StoryMemory)",
    storyMemorySubtitle:
      "이 항목들은 역추적 및 검색에 사용됩니다. 수동으로 추가/편집/병합/완료 표시/삭제할 수 있습니다. 자동 업데이트（plot_auto_update）도 플롯 메모리에만 기록되며 세계관 설정은 변경되지 않습니다.",
  },
  vectorRag: {
    title: "벡터 검색（Vector RAG）",
    subtitle: "Embedding은 텍스트를 벡터로 변환하여 검색에 사용하고, Rerank는 후보 결과를 재정렬하여 정확도를 높입니다(시간/비용이 증가할 수 있습니다).",
    apiKeyHint: "API Key는 암호화 저장되며 마스킹 표시됩니다. 비워두면 백엔드 환경 변수를 사용합니다.",
    save: "RAG 설정 저장",
    dryRunTitle: "설정 테스트 (dry-run)",
    backendEnvFallbackHint: "설정이 불확실한 경우 비워두면 백엔드가 환경 변수에서 자동으로 읽어옵니다.",
    pendingClearSuffix: " | 저장 시 내용이 삭제됩니다.",
    rerankTitle: "Rerank(재정렬)",
    rerankConfigDetailsTitle: "Rerank 제공자 설정",
    rerankProviderLabel: "Rerank 제공자(provider, 프로젝트 재정의, 비워두면=백엔드 환경 변수 사용)",
    rerankBaseUrlLabel: "Rerank 기본 주소(base_url, 프로젝트 재정의, 비워두면=백엔드 환경 변수 사용)",
    rerankModelLabel: "Rerank 모델(model, 프로젝트 재정의, 비워두면=백엔드 환경 변수 사용)",
    rerankTimeoutLabel: "Rerank 타임아웃(timeout_seconds, 프로젝트 재정의, 비워두면=백엔드 환경 변수 사용)",
    rerankHybridAlphaLabel: "Hybrid Alpha(0-1, 비워두면=0)",
    rerankApiKeyLabel: "Rerank API Key(api_key, 프로젝트 재정의, 비워두면 변경 안 함)",
    rerankClearApiKey: "프로젝트 수준 Rerank API Key 삭제",
    rerankResetOverrides: "백엔드 환경 변수 사용으로 복원 (프로젝트 재정의 초기화)",
    embeddingTitle: "Embedding(벡터화) 설정",
    embeddingClearApiKey: "프로젝트 수준 API Key 삭제",
  },
  structuredMemory: {
    title: "그래프 기반 데이터（StructuredMemory）",
    subtitle: "그래프 기반 데이터 테이블: 엔티티 / 관계 / 이벤트 / 복선 / 증거（인물 관계 편집 및 롤백 포함）.",
    usageHint: "언제 사용해야 할까요: “지식 그래프 추출” 오류 해결./점진적 업데이트./“주입” 기능이 기본 데이터 테이블에 직접 적용되는지, 아니면 키워드 검색 및 데이터 추출 기능을 통해 적용되는지 확인해야 합니다. (단, 이 기능은 숫자 데이터 표가 아닌 다른 형태의 데이터에 적용됩니다.)。",
    exampleHint: "예시: 검색창에 인물 이름을 입력한 후 “관계” 탭으로 전환합니다./“증거” 관찰 결과와 수량 변화의 일치 여부.。",
    bulkOpsHint: "일괄 작업은 Memory Update의 ops JSON을 생성합니다. 복사 후 Memory Update에 붙여넣고 Apply해야 적용됩니다.",
    bulkOpsRisk: "주의: Apply는 메모리 테이블을 직접 수정합니다. 선택 범위를 먼저 확인하고, 필요한 경우 JSON 백업을 먼저 복사하세요.",
    tabs: {
      entities: "엔티티",
      relations: "관계",
      events: "이벤트",
      foreshadows: "복선",
      evidence: "증거",
    },
    includeDeleted: "삭제된 항목 포함(include_deleted)",
    copyDeleteOps: "삭제 작업 JSON 복사",
    copyResolvedOps: "해결됨 표시 JSON 복사",
    deleteOpsLabel: "삭제 작업(delete ops)",
    resolvedOpsLabel: "해결됨으로 표시 (resolved ops)",
  },
  auth: {
    noAccountHint: "계정이 없으신가요?",
    goRegister: "회원가입하기",
    haveAccountHint: "이미 계정이 있으신가요?",
    goLogin: "로그인하기",
    loginTitle: "로그인",
    loginSubtitle: "로컬 계정으로 로그인（로그인 상태는 브라우저 Cookie에 저장；데이터는 서버 데이터베이스에 저장）",
    devFallbackHint: "개발 데모 모드가 활성화되었습니다: 로그인 없이 앱에 접근할 수 있습니다.",
    devFallbackRiskHint: "중요: 로컬 개발/데모 전용입니다. 공개 네트워크에 배포할 때는 반드시 dev_fallback을 비활성화하여 로그인 우회를 방지하세요.",
    devFallbackNextStepHint: "권한/협업/다중 사용자가 필요한 경우 아래에서 계정으로 로그인해 주세요.",
    continueInDevFallback: "앱으로 계속 이동",
    userIdLabel: "사용자 이름",
    userIdPlaceholder: "예: admin",
    passwordLabel: "비밀번호",
    passwordPlaceholder: "비밀번호를 입력해 주세요.",
    confirmPasswordLabel: "비밀번호 확인",
    confirmPasswordPlaceholder: "비밀번호를 다시 입력해 주세요.",
    passwordHint: "비밀번호는 8자 이상이어야 해요",
    reset: "비우기",
    login: "로그인",
    loggingIn: "로그인 중...",
    loginSuccess: "로그인 성공",
    loginFooterHint: "안내: 로그인 상태는 브라우저 Cookie에 저장됩니다. 로그아웃 시 로컬 로그인 상태가 초기화됩니다.",
    registerTitle: "회원가입",
    registerSubtitle: "로컬 계정 만들기(아이디/비밀번호)",
    register: "회원가입 및 로그인",
    registering: "가입 중...",
    registerSuccess: "회원가입 성공",
    logout: "로그아웃",
    sessionExpireAtPrefix: "세션 만료：",
    devFallbackTag: "로컬 모드 (DEV)",

    linuxdoLogin: "LinuxDo 원클릭 로그인/회원가입",
    linuxdoLoginFailedPrefix: "LinuxDo 로그인 실패:",
    linuxdoNotEnabledHint:
      "LinuxDo 로그인이 활성화되지 않았습니다. 백엔드 환경 변수에서 LINUXDO_OIDC_CLIENT_ID / LINUXDO_OIDC_CLIENT_SECRET / LINUXDO_OIDC_REDIRECT_URI를 설정해 주세요.",
    linuxdoCheckFailedPrefix: "LinuxDo 설정을 확인할 수 없습니다:",
  },
  writing: {
    contextPreview: "컨텍스트 미리보기",
    contextPreviewTitle: "컨텍스트 미리보기",
    contextPreviewSubtitle: "MemoryContextPack / logs",
    contextPreviewRefresh: "새로고침",
    contextPreviewClose: "닫기",
    contextPreviewLoadFailedTitle: "로드 실패",
    contextPreviewMissingProjectId: "projectId가 없습니다.",
    memoryInjectionToggle: "월드북 주입",
    memoryInjectionHint:
      "활성화 시: 생성 중 세계관/기억 등 모듈의 결과가 프롬프트에 주입됩니다. 컨텍스트 미리보기에서 트리거된 항목과 최종 주입 텍스트를 확인할 수 있습니다.",
    memoryInjectionDisabledPreview: "월드북 주입이 꺼져 있습니다. 활성화하면 트리거 항목과 text_md를 확인할 수 있습니다.",
    worldbookSectionTitle: "월드북（WorldBook）",
    contextPreviewRawPack: "raw MemoryContextPack",
    memoryPackEmpty: "현재 빈 패키지입니다 (Phase 0 자리 표시자).",
    memoryUpdateDrawer: {
      title: "메모리 업데이트 (Memory Update)",
      subtitle: "3단계：제안 → 검토 → 적용（Propose/Review/Apply）",
      step1: "단계 1: 제안 (Propose)",
      step2: "단계 2: 검토 (Review)",
      step3: "단계 3: 적용 (Apply)",
      step1Hint: "제안: 구조화된 메모리에 대한 변경 제안을 담은 일련의 제안서를 생성하되, 즉시 적용하지는 않습니다.。",
      step2Hint: "변경 사항을 적용하기 전에 각 변경 사항을 개별적으로 검토하고, 먼저 “변경 전” 내용을 확인하는 것이 좋습니다./변경 후.”。",
      step3Hint: "적용: 수락된 항목을 데이터베이스에 저장합니다. 반복 클릭은 멱등성이 보장됩니다 (중복 저장 없음).",
      inputTitle: "입력（JSON, 선택 사항）",
      inputHint: "고급 사용법: ops 배열 또는 ops 필드를 포함한 객체를 지원합니다.",
      focusLabel: "관심 포인트 (선택 사항)",
      focusPlaceholder: "예: 캐릭터 관계만 업데이트 / 이벤트만 추가",
      jsonLabel: "변경 지시（memory_update_json）",
      autoPropose: "한 번에 제안 생성（Auto Propose）",
      propose: "제안 생성 (Propose)",
      proposing: "생성 중...",
      proposeFailed: "제안 (Propose) 실패",
      reviewTitle: "변경 차이",
      accept: "수락",
      diffPreview: "변경 사항 미리보기",
      before: "변경 전",
      after: "변경 후",
      applyAccepted: "수락된 항목 적용 (Apply)",
      applying: "적용 중...",
      applyFailed: "적용 (Apply) 실패",
      retryApply: "앱 다시 시도",
      applyResultTitle: "적용 결과 (Apply Result)",
      warnings: "경고",
      warningsZero: "경고: 0",
      missingProposeHint: "먼저 “단계”에서 1”제안 초안 작성.Propose）。",
    },
    foreshadowDrawer: {
      title: "복선 패널",
      openCountLabel: "열린 복선",
      openOnlyHint: "안내: 여기에는 회수되지 않은 복선만 표시됩니다. 회수 표시 후 목록에서 제거됩니다.",
      hasMoreTag: "（has_more）",
      requestIdPrefix: "request_id:",
      refresh: "새로고침",
      refreshing: "로딩 중...",
      filterLabel: "필터",
      filterPlaceholder: "키워드 입력（여러 단어는 공백으로 구분）",
      filterHint: "제목/본문 미리보기/챕터 ID로 필터링할 수 있습니다. 여러 키워드는 공백으로 구분하세요.",
      empty: "아직 숨겨진 내용을 공개할 단계가 아닙니다. 먼저 “장 분석”에서 내용을 저장해두었다가 다시 확인해 보세요.。",
      noTitle: "(제목 없음)",
      metaChapterId: "챕터",
      metaScore: "중요도",
      metaTimeline: "타임라인",
      jumpChapter: "챕터 열기",
      annotatePage: "주석 페이지",
      resolve: "회수로 표시",
      resolveConfirmTitle: "복선 회수 완료로 표시할까요?",
      resolveConfirmText: "회수로 표시",
      resolveCancelText: "취소",
      resolveDoneToast: "휴지통으로 표시되었습니다",
      contentEmpty: "(비어 있음)",
    },
  },
  worldbook: {
    entriesCountPrefix: "총 ",
    entriesCountSuffix: " 개",
    refresh: "새로고침",
    create: "새 항목 만들기",

    bulkMode: "일괄 모드",
    bulkModeHint: "일괄 모드에서: 항목 클릭 = 선택/해제, 전체 선택 시 현재 필터 결과의 모든 항목이 선택됩니다.",
    bulkSelectedPrefix: "선택됨: ",
    bulkSelectedSuffix: " 개",
    bulkSelectAll: "전체 선택",
    bulkClearSelection: "선택 비우기",
    bulkEnable: "일괄 활성화",
    bulkDisable: "일괄 비활성화",
    bulkPriority: "우선순위（priority）",
    bulkCharLimit: "글자 수 제한 (char_limit)",
    bulkApply: "적용",
    bulkDelete: "일괄 삭제",
    bulkDuplicateEdit: "복사 후 편집",
    bulkNoSelection: "먼저 항목을 선택해 주세요.",

    bulkEnableTitle: "항목을 일괄 활성화할까요?",
    bulkEnableDescPrefix: "활성화될 항목: ",
    bulkEnableDescSuffix: " 개。",
    bulkDisableTitle: "항목을 일괄 비활성화할까요?",
    bulkDisableDescPrefix: "비활성화될 예정: ",
    bulkDisableDescSuffix: " 개。",
    bulkUpdateTitle: "항목을 일괄 업데이트할까요?",
    bulkUpdateDescPrefix: "업데이트될 항목: ",
    bulkUpdateDescSuffix: " 개。",
    bulkDeleteTitle: "항목을 일괄 삭제할까요?",
    bulkDeleteDescPrefix: "삭제될 예정: ",
    bulkDeleteDescSuffix: " 삭제하면 복구할 수 없습니다.。",
    bulkDuplicateTitle: "항목을 복사할까요?",
    bulkDuplicateDescPrefix: "복사될 항목: ",
    bulkDuplicateDescSuffix: " 문장을 선택하여 편집 모드로 들어갑니다.。",

    entriesTitle: "항목 목록",
    entriesHint:
      "키워드가 일치해야만 적용됩니다. (항상 적용됩니다.)constant）항목: 항상 적용하면 예산이 소모되므로, 필요한 경우에만 제한적으로 사용하는 것이 좋습니다. 항목 수가 많을 경우 목록이 여러 페이지로 나뉘어 표시되며, “더 보기”를 클릭하면 나머지 항목이 추가로 로드됩니다.。",
    empty: "항목이 없습니다",

    tagEnabled: "활성화",
    tagDisabled: "비활성화",
    tagBlue: "상주",
    tagGreen: "키워드",
    tagPriorityPrefix: "priority:",
    tagCharLimitPrefix: "limit:",
    keywordsPrefix: "키워드:",
    keywordsNone: "없음",

    previewTitle: "미리보기 트리거",
    previewHint: "query_text를 입력하여 어떤 항목이 트리거되는지와 최종 조합된 text_md를 확인하세요.",
    previewRun: "미리보기",
    previewQueryLabel: "query_text",
    previewIncludeConstant: "상시 항목 포함(constant)",
    previewEnableRecursion: "재귀 허용",
    previewCharLimit: "연결 문자 최대 길이",
    previewRequiresSaveHint: "현재 항목에 저장되지 않은 변경 사항이 있습니다. 미리보기는 저장된 항목을 기준으로 하므로, 먼저 저장한 후 미리보기를 확인하세요.",
    previewUseInDrawerHint: "편집 패널이 열려 있을 때는 패널 내에서 미리보기를 실행해 주세요.",
    previewFailed: "미리보기 실패",
    previewTriggeredPrefix: "트리거 ",
    previewTriggeredSuffix: " 개",
    previewTruncated: "잘렸습니다 (상한 초과)",
    previewTriggeredList: "항목 트리거",
    previewNoTriggered: "트리거된 항목이 없습니다",
    previewText: "text_md(최종 주입 텍스트)",
    previewTextEmpty: "(비어 있음)",

    drawerTitle: "세계관 항목 편집",
    newEntryHint: "새 항목",
    close: "닫기",
    cancel: "취소",

    formTitle: "제목",
    formEnabled: "활성화",
    formConstant: "상주 (constant)",
    formExcludeRecursion: "재귀 제외",
    formPreventRecursion: "재귀 차단",
    formKeywords: "키워드 (한 줄에 하나씩)",
    formKeywordsHint: "매칭 트리거에 사용합니다 (비상주 항목에만 적용).",
    formCharLimit: "글자 수 제한",
    formPriority: "우선순위",
    formContent: "내용 (Markdown)",

    save: "저장",
    saving: "저장 중...",
    saved: "저장되었습니다",

    delete: "삭제",
    deleted: "삭제되었습니다",

    discardChangesTitle: "저장하지 않은 변경 사항을 버릴까요?",
    discardChangesDesc: "닫기 전에 저장되지 않은 변경 사항이 삭제됩니다.",
    discardChangesConfirm: "버리기",
    discardChangesCancel: "계속 편집",

    validationTitleRequired: "제목을 입력해 주세요",

    deleteTitle: "이 항목을 삭제할까요?",
    deleteDesc: "삭제 후 복구할 수 없습니다.",
    deleteConfirm: "삭제",
    deleteCancel: "취소",

    missingProjectId: "projectId가 없습니다.",
  },
  rag: {
    title: "Vector RAG 관리",
    subtitle: "상태. / 조회하다. / 검색하다. / 문의하다. / 확인하다. / 입고. / 인덱스를 재구축하여 “주입이 제대로 적용되지 않는” 문제를 해결합니다./정확도가 떨어지다. / 명중률이 낮다. / 결과가 예측하기 어렵다./인덱스가 만료되었습니다.”。",
    usageHint: "글을 쓸 때 “세상이 다 담겨 있는 듯한” 느낌이 들 때 사용하세요./컨텍스트 주입이 제대로 작동하지 않거나 검색 결과가 불안정할 때, 먼저 이 페이지에서 상태 및 적중 여부를 확인해 보세요.。",
    exampleHint: "예시: 챕터의 일부 내용이나 키워드(예: )를 입력하세요.“dragon”）“검색”을 클릭하여 일치하는 결과와 삽입 결과를 확인하세요.。",
    riskHint: "주의: 색인 저장/재구성에 시간이 걸릴 수 있으며, 온라인 모델로 구성된 경우 비용이 발생할 수 있습니다.",

    settings: "모델 설정 (Vector RAG)",
    ingest: "인제스트 트리거 (Ingest)",
    rebuild: "인덱스 재구축（Rebuild）",
    rebuildNeedConfig: "인덱스 재구축（Rebuild, 설정 필요）",
    rebuildRecommended: "인덱스 재구축（Rebuild, 권장）",

    kbTitle: "지식 베이스 (KB)",
    kbOrderLabel: "정렬 (order)",
    kbEnabledLabel: "활성화（enabled）",
    kbWeightLabel: "가중치 (weight)",
    kbNameLabel: "이름（name）",
    kbNewNameLabel: "새 지식 베이스 이름 (name)",
    kbNewNamePlaceholder: "예: 나의 지식 베이스",

    sourcesTitle: "조회 출처",
    queryTitle: "조회",
    injectionTitle: "주입 결과",
    advancedDebugTitle: "고급 디버그",
    rerankTitle: "재정렬（Rerank）",

    ingestResultTitle: "입수 결과 (Ingest result)",
    rebuildResultTitle: "재구축 결과（Rebuild result）",
  },
  graph: {
    title: "그래프",
    subtitle: "그래프 컨텍스트（GraphContext）: 쿼리 매칭 엔티티 + 1-hop 관계 + 증거 재생. 인물 관계 편집으로 이동을 지원합니다.",
    usageHint: "언제 사용하면 좋을까요? “어떤 개체를 확인하고 싶을 때”/관계가 식별되어 연결되거나, 검색 결과에서 바로 인물 관계 편집으로 이동합니다./증거 위치 파악.。",
    exampleHint: "예시: 챕터의 문장 하나를 검색창에 복사하여 붙여넣은 후 “검색”을 클릭하면 해당 문장과 관련된 정보 및 출처를 확인할 수 있습니다.。",
    riskHint: "주의: 이 페이지는 고급 디버그 페이지로 일부 원시 결과 및 증거 단편이 표시됩니다. 공유 환경에서 프로젝트 내용이 노출되지 않도록 주의하세요.",

    enabledToggle: "활성화（enabled）",
    queryTextLabel: "조회 텍스트 (query_text)",
    queryTextPlaceholder: "챕터 텍스트 또는 핵심 단락 입력（엔티티 이름/별칭 매칭）",
    queryRun: "조회",

    autoUpdateTitle: "자동 업데이트 작업 (graph_auto_update)",
    autoUpdateFocusLabel: "focus(선택 사항)",
    autoUpdateFocusPlaceholder: "선택사항: 이번에 집중할 엔티티/관계/단편",
    autoUpdateCreateButton: "자동 업데이트 작업 만들기",
    autoUpdateCreatedToast: "자동 업데이트 작업이 생성되었습니다",
    autoUpdateMissingChapterId: "chapterId가 없습니다. 작성 페이지에서 이동하거나 URL에 ?chapterId=<...>를 추가해 주세요.",
    autoUpdateLastTaskIdLabel: "last_task_id",
    autoUpdateOpenTaskCenter: "작업 센터 열기",
    autoUpdateCopyTaskId: "task_id 복사",

    overviewTitle: "결론 요약",
    injectionPreviewTitle: "주입 미리보기 (prompt_block.text_md)",
    nodesTitle: "노드",
    matchedLabel: "매칭됨（matched）",
    relationsTitle: "관계",
    evidenceTitle: "증거 (source_id 매칭 노드/엣지)",
    advancedDebugTitle: "고급 디버그(raw graph query result)",
  },
  promptStudio: {
    titleBeta: "프롬프트 스튜디오 (beta)",
    loadingA11y: "프롬프트 스튜디오 불러오는 중…",
    missingProjectId: "projectId가 없습니다.",
    processing: "처리 중…",

    previewNote: "미리보기는 백엔드 렌더링 인터페이스를 통해 생성됩니다.",
    backToPrompts: "모델 설정으로 돌아가기",
    newbiePromptTemplates: "초보자: Prompt 템플릿",
    goWriting: "글쓰기로 이동",

    intro: "여기서 프리셋과 프롬프트 블록을 관리하고 백엔드 렌더링 미리보기를 생성합니다.",
    recommendedFlow: "권장 흐름: 모델 설정 → (초보자 템플릿/스튜디오) → 개요 생성 → 챕터 생성 → 기억 업데이트",
    quickStart: "빠르게 시작하려면: 미리 설정된 옵션을 선택하세요. → 편집 템플릿 조각. → 오른쪽 미리보기. → 작성 페이지로 돌아가려면 클릭하세요.“AI 생성.”。",
    advancedHint: "참고: 이곳은 고급 모드입니다. ‘핵심 키워드’만 변경하고 싶다면 ‘초급’ 모드에서 시작하는 것이 좋습니다.Prompt “템플릿” 시작.。",

    conceptTitle: "개념 설명 (프리셋/프롬프트 블록/우선순위)",

    enableRecommendedPresets: "추천 프리셋 원클릭 활성화(개요/챕터)",

    toastRecommendedNotFound: "추천 프리셋을 찾을 수 없습니다. 새로고침 후 다시 시도해 주세요.",
    toastRecommendedEnabled: "추천 프리셋이 활성화되었습니다: 개요/챕터",
    toastPresetSaved: "프리셋이 저장되었습니다",
    toastPresetDeleted: "프리셋이 삭제되었습니다",
    toastBlockSaved: "블록이 저장되었습니다",
    toastBlockDeleted: "블록이 삭제되었습니다",
    toastReordered: "정렬이 업데이트되었습니다",

    confirmDeletePresetTitle: "프리셋을 삭제할까요?",
    confirmDeletePresetConfirm: "삭제",
    confirmDeleteBlockTitle: "블록을 삭제할까요?",
    confirmDeleteBlockConfirm: "삭제",
    confirmDeleteBlockDescFallback: "이 프롬프트 블록이 삭제됩니다.",

    tasks: {
      outlineGenerate: "개요 (outline_generate)",
      chapterGenerate: "챕터 (chapter_generate)",
      planChapter: "플래닝 (plan_chapter, M3)",
      postEdit: "윤문 (post_edit, M3)",
      contentOptimize: "본문 최적화 (content_optimize, P0)",
      chapterAnalyze: "챕터 분석 (chapter_analyze, P2)",
      chapterRewrite: "챕터 재작성 (chapter_rewrite, P2)",
    },
  },
  fractal: {
    title: "분형 기억(Fractal)",
    tag: "Fractal",
    subtitle: "프랙탈 메모리 주입 텍스트를 확인/재생하여 메모리 주입 및 요약이 예상대로 작동하는지 진단하는 데 사용합니다.",
    usageHint: "언제 사용해야 하는가: 글을 쓰던 중 “메모리 주입이 제대로 작동하지 않음”이라는 문제가 발생했을 때./요약 내용에 오류가 있습니다./맥락이 일관되지 않거나 하는 문제에 직면했을 때.。",
    riskHint: "주의: 이 페이지는 고급 디버그 페이지로 일부 prompt/내부 상태가 표시됩니다. 공유 환경에서 프로젝트 내용이 노출되지 않도록 주의하세요.",
  },
  taskCenter: {
    title: "작업 센터",
    subtitle: "기억 변경 집합 및 백그라운드 작업의 상태, 오류, 문제 해결 정보를 확인해요.",
    usageHint: "사용 시점：생성 / 기억 업데이트 후 결과가 예상과 다르거나, 백그라운드 작업의 실패 / 대기 / 실행 여부를 확인해야 할 때.",
    riskHint: "주의: 이 페이지에는 다수의 디버그 필드(request_id/error 등)가 포함되어 있습니다. 외부 공유 시 민감 정보를 마스킹하세요.",
  },
  featureDefaults: {
    ariaLabel: "기본 동작(Feature Defaults)",
    title: "기본 동작 (기본 활성화)",
    subtitle: "일반 사용자는 기억 주입 및 백그라운드 자동 업데이트가 기본으로 활성화됩니다. 고급 사용자는 비용 절감 및 속도 향상을 위해 필요에 따라 비활성화할 수 있어요.",
    memoryInjectionLabel: "글쓰기 시 기본으로 기억 주입(Memory Injection) 활성화",
    memoryInjectionHint:
      "비활성화 후: 챕터 생성/컨텍스트 미리보기 시 세계관 설정/기억 모듈이 기본적으로 주입되지 않습니다. 작성 페이지에서 임시로 활성화할 수 있습니다(비용 절감/문제 해결에 권장).",
    reset: "기본값으로 복원 (활성화)",
    resetHint: "현재 브라우저에만 적용됩니다（localStorage；언제든지 전환 가능）.",
    toastEnabled: "활성화됨: 글쓰기 기본 메모리 주입",
    toastDisabled: "비활성화됨: 글쓰기 기본 메모리 주입",
    toastReset: "기본값으로 복원됨: 글쓰기 기본 메모리 주입 (활성화)",
    autoUpdateHint:
      "백그라운드 자동 업데이트（세계관/그래프/벡터/검색）기본 활성화: 챕터 확정/내용 변경 후 자동으로 작업이 예약됩니다. 「작업 센터」에서 상태 확인 및 재시도 가능합니다.",
  },
} as const;
