export const TASK_CENTER_COPY = {
  missingProjectId: "projectId가 없어요",
  loading: "로딩 중...",
  processing: "처리 중...",
  allOption: "전체",
  refresh: "새로고침",
  requestIdCopyTitle: "복사 실패: 요청 ID(request_id)를 직접 복사해주세요",
  runIdCopyTitle: "복사 실패: run_id를 직접 복사해주세요",
  copyDebugInfoTitle: "Copy debug info manually",
  cancelQueuedProjectTaskConfirm: "대기열의 작업을 취소할까요? 취소하면 실행되지 않아요.",
  cancelBatchConfirm: "현재 배치 작업을 취소할까요? 취소하면 이 배치는 계속 실행되지 않아요.",
  unknownErrorType: "ERROR",
  unknownErrorMessage: "알 수 없는 오류",

  queueStatusAria: "큐 상태 (taskcenter_queue_status)",
  queueBackendLabel: "설정된 백엔드 (queue_backend)",
  effectiveBackendLabel: "실제 백엔드 (effective_backend)",
  redisOkLabel: "redis_ok",
  queueNameLabel: "queue",
  queueInlineWarning: "안내: inline은 프로세스 내부 단일 스레드 워커라 작업이 순차적으로 실행돼요. 동시성이 필요하면 rq+worker를 켜주세요.",
  queueHealthCopyButton: "health 요청 ID(request_id) 복사",

  usageLinksPrefix: "자주 쓰는 입구: ",
  helpStructuredMemory: "구조화 기억",
  helpWriting: "집필 페이지",
  helpUsageSuffix: " 사이를 오가며 '제안→적용→롤백' 전체 흐름을 확인하세요.",

  changeSetsSectionAria: "변경집 (taskcenter_changesets_section)",
  changeSetsTitle: "변경집 (Change Set)",
  changeSetsHint: "상태별로 필터링. 항목을 클릭하면 요약과 원본 데이터가 열려요 (기본 접힘)",
  changeSetsStatusHint: "상태 설명: 미적용=제안만 | 적용됨=DB 반영 | 롤백됨=취소 | 실패=실행 예외",
  changeSetsEmpty: "변경집이 없어요",
  changeSetsStatusLabel: "상태",
  countLabels: {
    all: "전체",
    queued: "대기 중",
    running: "실행 중",
    done: "완료",
    failed: "실패",
  },
  changeSetsCounts: {
    all: "전체",
    proposed: "미적용",
    applied: "적용됨",
    rolledBack: "롤백됨",
    failed: "실패",
  },

  tasksSectionAria: "작업 목록 (taskcenter_tasks_section)",
  tasksTitle: "작업 (Task)",
  tasksHintPrefix: "실패한 작업은 오류 요약과 ",
  tasksStatusHint: "상태 설명: 대기 중→실행 중→완료/실패 (실패 시 request_id로 백엔드 로그 확인 가능)",
  tasksEmpty: "작업이 없어요",
  tasksFailedOnly: "실패만 보기",

  projectTasksSectionAria: "프로젝트 작업 (taskcenter_projecttasks_section)",
  projectTasksTitle: "프로젝트 작업 (Project Task)",
  projectTasksHint:
    "worldbook/search/vector/graph 등의 자동 백그라운드 업데이트용. 항목을 클릭하면 상세(params/result/error 마스킹됨)가 보여요",
  projectTasksStatusHint: "상태 설명: 대기 중→실행 중→완료/실패",
  projectTasksLiveStatusPrefix: "Project SSE: ",
  projectTasksLiveLabels: {
    idle: "idle",
    connecting: "reconnecting",
    open: "connected",
    error: "fallback polling",
  },
  projectTasksEmpty: "프로젝트 작업이 없어요",
  projectTasksFailedOnly: "실패만 보기",
  projectTasksRetry: "재시도",
  projectTasksCancel: "취소",
  projectTasksRetryToast: "작업을 재시도했어요",
  projectTasksCancelToast: "작업을 취소했어요",
  projectTasksIdempotencyPrefix: "멱등 키: ",

  detailCopyDebug: "Debug 정보 복사",
  detailClose: "닫기",
  detailOverview: "Overview",
  detailActions: "Actions",
  detailGenerationRun: "GenerationRun",
  detailError: "Error",
  detailChangeSet: "ChangeSet",
  detailResults: "Results",
  detailRawJson: "원본 데이터 (JSON)",
  detailNoError: "오류 정보가 없어요",
  detailMissingChangeSet: "이 작업의 result에 change_set이 포함되어 있지 않아요 (아직 실행 중이거나 실패했을 수 있어요).",
  detailApplyRollbackHint: "안내: Apply/Rollback은 editor 권한이 필요해요. 실패 시 request_id를 복사해 문제 해결에 활용하세요.",
  detailRefreshProjectTask: "상세 새로고침",
  detailApplyChangeSetToast: "ChangeSet을 적용했어요",
  detailRollbackChangeSetToast: "ChangeSet을 롤백했어요",

  requestIdCopyButton: "요청 ID(request_id) 복사",
  projectTaskRunIdCopyButton: "run_id 복사",
  projectTaskRunIdOpenButton: "실행 기록 열기",
  applyChangeSetButton: "Apply",
  rollbackChangeSetButton: "Rollback",

  runtimeTitle: "Runtime",
  runtimeRefreshButton: "Refresh runtime",
  runtimeEmpty: "No unified runtime data yet.",
  runtimeBatchTitle: "Batch",
  runtimeArtifactsTitle: "Artifacts",
  runtimeTimelineTitle: "Timeline",
  runtimeNoBatchItems: "No batch steps yet.",
  runtimeNoTimeline: "No timeline events yet.",
  runtimeOpenGenerationRun: "Open generation run",
  runtimeBatchPause: "Pause",
  runtimeBatchResume: "Resume",
  runtimeBatchRetryFailed: "Retry failed chapters",
  runtimeBatchSkipFailed: "Skip failed chapters",
  runtimeBatchCancel: "Cancel batch",
  runtimeBatchWorking: "Working...",
  runtimeBatchPausedToast: "Batch paused.",
  runtimeBatchResumedToast: "Batch resumed.",
  runtimeBatchRetryFailedToast: "Failed chapters queued for retry.",
  runtimeBatchSkipFailedToast: "Failed chapters skipped.",
  runtimeBatchCanceledToast: "Batch canceled.",
} as const;
