type WorldBookActionError = {
  message: string;
  code: string;
};

export const WORLDBOOK_COPY = {
  exportJson: "JSON 내보내기",
  exporting: "내보내는 중...",
  importJson: "JSON 가져오기",
  exportSuccess: "JSON을 내보냈어요",
  exportFailed: "내보내기에 실패했어요",

  autoUpdateTitle: "세계책 자동 업데이트",
  autoUpdateHint: "장이 탈고되면 백그라운드에서 항목을 추출해 병합해요. 실패해도 집필에는 영향 없으며 재시도할 수 있어요.",
  autoUpdateRefresh: "상태 새로고침",
  autoUpdateRetry: "재시도",
  autoUpdateTrigger: "수동 실행",
  autoUpdateProcessing: "처리 중...",
  autoUpdateTriggeredToast: "세계책 자동 업데이트를 실행했어요 (백그라운드 작업)",
  autoUpdateRetryToast: "재시도 요청을 제출했어요",
  autoUpdateTriggerFailed: "실행에 실패했어요",
  autoUpdateRetryFailed: "재시도에 실패했어요",
  autoUpdateEmpty: "작업 기록이 아직 없어요 (장이 탈고되면 자동으로 생성됩니다).",
  autoUpdateTaskCenter: "작업 센터",
  autoUpdateRequestId: "request_id:",
  autoUpdateChapterId: "chapter_id:",
  autoUpdateRunId: "run_id:",
  autoUpdateApplied: "applied:",
  autoUpdateFailedFallback: "작업이 실패했어요",

  searchLabel: "검색 (제목 / 키워드)",
  searchPlaceholder: "dragon",
  sortLabel: "정렬",
  sortOptions: [
    { value: "updated_desc", label: "수정 시간 (updated_at) ↓" },
    { value: "updated_asc", label: "수정 시간 (updated_at) ↑" },
    { value: "priority_desc", label: "우선순위 (priority) ↓" },
    { value: "priority_asc", label: "우선순위 (priority) ↑" },
    { value: "enabled_desc", label: "활성화 (enabled) ↓" },
    { value: "enabled_asc", label: "활성화 (enabled) ↑" },
  ] as const,
  priorityOptions: [
    { value: "must", label: "필수 (must)" },
    { value: "important", label: "중요 (important)" },
    { value: "optional", label: "선택 (optional)" },
    { value: "drop_first", label: "먼저 버림 (drop_first)" },
  ] as const,
  pinyinTag: "병음",
  paginationInfoPrefix: "표시 중 ",
  paginationInfoMiddle: " 개 (초과 시 ",
  paginationInfoSuffix: " 개부터 페이지네이션)",
  paginationPagePrefix: "",
  paginationPageSeparator: "/",
  paginationPageSuffix: " 페이지",
  paginationPrev: "이전",
  paginationNext: "다음",
  hiddenSelectionPrefix: "(숨겨진 ",
  hiddenSelectionSuffix: " 개 포함)",

  bulkConfirmText: "확인",
  bulkUpdatedToast: "일괄 업데이트 완료",
  bulkDeletedToast: "일괄 삭제 완료",
  bulkUpdateFailed: "일괄 업데이트에 실패했어요",
  bulkDeleteFailed: "일괄 삭제에 실패했어요",
  duplicateConfirmText: "복제",
  duplicateFailed: "복제에 실패했어요",
  duplicateFailedEmpty: "복제 실패: 반환값이 비어있어요",
  duplicateSuccess: "복제하고 편집 상태로 전환했어요",
  duplicateRequiresSingle: "복제 후 편집은 1개 항목을 선택해야 해요",

  importDrawerTitle: "세계책 가져오기",
  importDrawerHint: "전체 내보낸 JSON(export_all)을 업로드하세요. dry_run 시뮬레이션으로 충돌을 확인한 뒤 적용할 수 있어요.",
  importFileTitle: "가져올 파일",
  importFileLabel: "JSON 파일 가져오기",
  importModeLabel: "가져오기 모드",
  importModeMerge: "merge (title 기준 생성/업데이트)",
  importModeOverwrite: "overwrite (전체 삭제 후 가져오기)",
  importModeHint: "merge: 같은 title은 업데이트. overwrite: 전체 삭제 후 가져오기 (위험, 재확인 필요).",
  importSelectedPrefix: "선택됨: ",
  importSchemaVersionLabel: "schema_version:",
  importEntriesLabel: "entries:",
  importDryRunButton: "dry_run 미리보기",
  importApplyButton: "가져오기 적용",
  importProcessing: "처리 중...",
  importApplying: "가져오는 중...",
  importLoadedToast: "파일을 불러왔어요",
  importParseFailed: "JSON 파싱에 실패했어요",
  importChooseFile: "먼저 가져올 JSON 파일을 선택해주세요",
  importFailed: "가져오기에 실패했어요",
  importOverwriteConfirmTitle: "덮어쓰기 가져오기를 확인할까요?",
  importOverwriteConfirmDescription: "overwrite는 현재 항목을 모두 삭제한 뒤 JSON을 가져와요.",
  importOverwriteConfirmText: "계속",
  importOverwriteCancelText: "취소",
  importDryRunDone: "dry_run 완료",
  importDone: "가져오기 완료",
  importPostApplyWarning: "세계책이 변경됐어요. RAG 페이지에서 지식베이스 인덱스를 다시 빌드하는 것을 권장해요.",
  importReportTitle: "가져오기 리포트",
  importReportExplain: "필드 설명: dry_run=시뮬레이션 (쓰지 않음), mode=merge 병합 업데이트 / overwrite 덮어쓰기.",
  importReportCountsExplain: "created 새로 만듦 | updated 업데이트 | deleted 삭제 | skipped 건너뜀",
  importReportConflicts: "충돌 (conflicts)",
  importReportActions: "변경 (actions)",
} as const;

export function formatWorldBookActionError(action: string, error: WorldBookActionError, options?: { count?: number }) {
  const countPrefix =
    typeof options?.count === "number" && Number.isFinite(options.count) ? `（${options.count}개）` : "";
  return `${action}${countPrefix}：${error.message} (${error.code})`;
}
